type: "DDSP"
precision: "32"
val_check: 5000
sample_rate: 44100
f_min: 40
f_max: 16000
n_mels: 128
hop_length: 512
win_length: 2048
n_fft: 2048
lr: 0.0004
lr_decay: 0.99
adam_b1: 0.8
adam_b2: 0.99
uv_detach_step: Null
uv_tolerance: 0.3
use_discriminator: False
dataset:
  train:
    path: "dataset/train"
    segment_length: 44032
    pitch_shift: [-12, 12]
    pitch_shift_prob: 1.0
    pitch_shifter: "RosaShifter"
    shift_f0: False
    loudness_shift: [0.1, 0.9]
    loudness_shift_prob: 1.0
    hap_shift: Null
    hap_shift_prob: 0.0
    reverse_prob: Null
    return_vuv: True
    return_original: True
    separate_sp_ap: False
  valid:
    path: "dataset/valid"
    segment_length: Null
    pitch_shift: Null
    pitch_shift_prob: 0.0
    loudness_shift: Null
    loudness_shift_prob: 0.0
    hap_shift: Null
    hap_shift_prob: 0.0
    reverse_prob: Null
    return_vuv: True
    separate_sp_ap: False
dataloader:
  train:
    batch_size: 32
    shuffle: True
    num_workers: 14
    pin_memory: True
    drop_last: True
    persistent_workers: True
    prefetch_factor: 2
  valid:
    batch_size: 4
    shuffle: False
    num_workers: 4
    pin_memory: True
    drop_last: True
    persistent_workers: True
    prefetch_factor: 1
model:
  input_noise: 0.0
mpd:
  periods:  [2, 3, 5, 7, 11]
  kernel_size: 5
  stride: 3
  lrelu_slope: 0.1
mrd:
  resolutions: [[1024, 120, 600], [2048, 240, 1200], [512, 50, 240]] # (filter_length, hop_length, win_length)
  lrelu_slope: 0.1
preprocessing:
  threads: 8
  f0_min: 40
  f0_max: 1400
  pitch_extractor:
    name: "ParselmouthPE"
    keep_zeros: False
  vuv: True
  vuv_smoothing: 2
  oversampling: 1
