type: "HiFiPLN"
precision: "16-mixed"
val_check: 500
sample_rate: 44100
f_min: 40
f_max: 16000
n_mels: 128
hop_length: 512
win_length: 2048
n_fft: 2048
lr: 0.00001
lr_decay: 0.99
adam_b1: 0.8
adam_b2: 0.99
finetune: ckpt/HiFiPLN.ckpt
dataset:
  train:
    path: "dataset/train"
    segment_length: 65536
    pitch_shift: Null
    loudness_shift: Null
  valid:
    path: "dataset/valid"
    segment_length: Null
    pitch_shift: Null
    loudness_shift: Null
dataloader:
  train:
    batch_size: 10
    shuffle: True
    num_workers: 8
    pin_memory: True
    drop_last: True
    persistent_workers: True
  valid:
    batch_size: 4
    shuffle: False
    num_workers: 4
    pin_memory: True
    drop_last: True
    persistent_workers: True
model:
  vuv_ckpt: "ckpt/VUV.ckpt"
  lrelu_slope: 0.1
  sine_amp: 0.3
  noise_amp: 0.015
  input_noise: 0.01
  harmonic_num: 8
  upsample_rates: [8, 8, 2, 2, 2]
  upsample_kernel_sizes: [16, 16, 8, 2, 2]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes:
    - [1, 3, 5]
    - [1, 3, 5]
    - [1, 3, 5]
model_vuv:
  lrelu_slope: 0.1
  channels: 512
  layers: 4
mpd:
  periods:  [2, 3, 5, 7, 11]
  kernel_size: 5
  stride: 3
  lrelu_slope: 0.1
mrd:
  resolutions: [[1024, 120, 600], [2048, 240, 1200], [512, 50, 240]] # (filter_length, hop_length, win_length)
  lrelu_slope: 0.1
preprocessing:
  f0_min: 40
  f0_max: 1400
  pitch_extractor:
    name: "ParselmouthPE"
    keep_zeros: False
  spectogram: False
  vuv: False
