sample_rate: 44100
f_min: 40
f_max: 16000
n_mels: 128
hop_length: 512
win_length: 2048
n_fft: 2048
lr: 0.0002
lr_decay: 0.999
adam_b1: 0.8
adam_b2: 0.99
dataset:
  train:
    path: "dataset/train"
    segment_length: 16384
    pitch_shift: Null
    # loudness_shift: Null
    speed_shift: Null
    # pitch_shift: [-12, 24]
    loudness_shift: [0.5, 1.0]
    # speed_shift: [0.9, 1.2]
  valid:
    path: "dataset/valid"
    segment_length: Null
    pitch_shift: Null
    loudness_shift: Null
    speed_shift: Null
dataloader:
  train:
    batch_size: 20
    shuffle: True
    num_workers: 4
    pin_memory: True
    drop_last: True
    persistent_workers: True
  valid:
    batch_size: 2
    shuffle: False
    num_workers: 2
    pin_memory: True
    drop_last: True
    persistent_workers: True
model:
  lrelu_slope: 0.1
  sine_amp: 0.2
  noise_std: 0.1
  harmonic_num: 8
  upsample_rates: [8, 8, 2, 2, 2]
  upsample_kernel_sizes: [16, 16, 8, 2, 2]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes:
    - [1, 3, 5]
    - [1, 3, 5]
    - [1, 3, 5]
  discriminator_periods:  [3, 5, 7, 11, 17, 23, 37]
preprocessing:
  f0_min: 40
  f0_max: 1400
  pitch_extractor:
    name: "ParselmouthPE"
    keep_zeros: False
  spectogram: False
