type: "HiFiPLNv1"
precision: "32"
val_check: 500
sample_rate: 44100
f_min: 40
f_max: 16000
n_mels: 128
hop_length: 512
win_length: 2048
n_fft: 2048
lr: 0.0002
lr_decay: 0.995
adam_b1: 0.8
adam_b2: 0.99
ddsp_detach_step: 50000
uv_tolerance: 0.05
input_noise: 0.0
dropout: 0.0
dataset:
  train:
    path: "dataset/train"
    segment_length: 16384
    pitch_shift: [-12, 12]
    pitch_shift_prob: 1.0
    loudness_shift: [0.25, 1.0]
    loudness_shift_prob: 1.0
    hap_shift: Null
    hap_shift_prob: 0.0
    reverse_prob: Null
    return_vuv: True
    separate_sp_ap: False
  valid:
    path: "dataset/valid"
    segment_length: Null
    pitch_shift: Null
    pitch_shift_prob: 0.0
    loudness_shift: Null
    loudness_shift_prob: 0.0
    hap_shift: Null
    hap_shift_prob: 0.0
    reverse_prob: Null
    return_vuv: True
    separate_sp_ap: False
dataloader:
  train:
    batch_size: 12
    shuffle: True
    num_workers: 8
    pin_memory: True
    drop_last: True
    persistent_workers: True
    prefetch_factor: 8
  valid:
    batch_size: 4
    shuffle: False
    num_workers: 4
    pin_memory: True
    drop_last: True
    persistent_workers: True
    prefetch_factor: 4
model:
  snake_log: True
  snake_upsample: False
  upsample_rates: [8, 8, 2, 2, 2]
  upsample_kernels: [16, 16, 4, 4, 4]
  upsample_initial: 512
  kernel_sizes: [3, 7, 11]
  dilation_sizes:
    - [1, 3, 5]
    - [1, 3, 5]
    - [1, 3, 5]
mpd:
  periods: [2, 3, 5, 7, 11, 17, 23, 37]
  kernel_size: 5
  stride: 3
  lrelu_slope: 0.1
mrd:
  resolutions: [[2048, 240, 1200], [1024, 120, 600], [512, 50, 240]] # (filter_length, hop_length, win_length)
  lrelu_slope: 0.1
preprocessing:
  threads: 8
  f0_min: 40
  f0_max: 1400
  pitch_extractor:
    name: "ParselmouthPE"
    keep_zeros: False
  vuv: True
  vuv_smoothing: 2
  oversampling: 1
