type: "HiFiPLNv2"
precision: "32"
val_check: 2000
sample_rate: 44100
f_min: 40
f_max: 16000
n_mels: 128
hop_length: 512
win_length: 2048
n_fft: 2048
log_accuracy: False
optimizer:
  type: "AdamW"
  lr: 0.0002
  lr_decay: 0.95
  lr_decay_steps: 50000
  weight_decay: 1e-4
  adam_b1: 0.8
  adam_b2: 0.99
  momentum: 0.9
  clip_percentile: 10.0
  clip_history: 44299
  clip_max: 500.0
source_detach_step: Null
uv_detach_step: 50000
uv_tolerance: 0.1
input_noise: 0.02
dropout: 0.01
loss_scale:
  gen_mpd: 1.0
  feat_mpd: 2.0
  gen_cqtd: 1.0
  feat_cqtd: 2.0
  mss: 45.0
  mel: 1.0
  envelope: 1.0
  symmetry: 1.0
  weight: 1.0
  source: 1.0
  uv_source: 1.0
  mss_source: 1.0
  mel_source: 1.0
  clipping_source: 1.0
dataset:
  train:
    path: "dataset/train"
    segment_length: 16384
    pitch_shift: [-12, 12]
    pitch_shift_prob: 1.0
    pitch_shifter: "RosaShifter"
    shift_f0: False
    loudness_shift: [0.1, 0.9]
    loudness_shift_prob: 1.0
    hap_shift: Null
    hap_shift_prob: 0.0
    reverse_prob: Null
    return_vuv: True
    return_original: True
    separate_sp_ap: False
  valid:
    path: "dataset/valid"
    segment_length: Null
    pitch_shift: Null
    pitch_shift_prob: 0.0
    loudness_shift: Null
    loudness_shift_prob: 0.0
    hap_shift: Null
    hap_shift_prob: 0.0
    reverse_prob: Null
    return_vuv: False
    separate_sp_ap: True
dataloader:
  train:
    batch_size: 8
    shuffle: True
    num_workers: 8
    pin_memory: True
    drop_last: True
    persistent_workers: True
    prefetch_factor: 2
  valid:
    batch_size: 2
    shuffle: False
    num_workers: 2
    pin_memory: True
    drop_last: True
    persistent_workers: True
    prefetch_factor: 1
norm:
  normalize: False
  mel_mean: 0.0
  mel_std: 1.0
  pitch_mean: 0.0
  pitch_std: 1.0
model:
  compile: False
  compile_mode: "default"
  activation: "SnakeGamma"
  encoder_layers: 3
  encoder_hidden: 256
  encoder_glu: "GeGLU"
  encoder_activation: "GELU"
  encoder_dropout: 0.1
  decoder_layers: 3
  decoder_hidden: 256
  decoder_glu: "GeGLU"
  decoder_activation: "GELU"
  decoder_dropout: 0.1
  detach_stft: False
  act_log: True
  act_upsample: False
  upsample_rates: [8, 4, 2, 2, 2, 2]
  upsample_kernels: [16, 8, 4, 4, 4, 4]
  upsample_initial: 1024
  channels_min: 16
  kernel_sizes: [3, 5, 7]
  dilation_sizes: [1, 3, 5]
  norm: "weight"
  filter_lowpass: False
  filter_highpass: False
mss:
  n_ffts: [2048, 1024, 512, 256, 128, 64, 32]
  overlap: 0.75
  eps: 1e-7
  use_mel: True
mpd:
  norm: "weight"
  periods:  [2, 3, 5, 7, 11, 17, 23, 37]
  kernel_size: 5
  stride: 3
  activation: "ReLU"
  lrelu_slope: 0.1
cqtd:
  norm: "weight"
  resolutions: [[256, 9, 24], [256, 9, 36], [256, 9, 48]] # (hop_length, octaves, bins_per_octave)
  resample: True
  filters: 128
  dilations: [1, 2, 4]
  activation: "ReLU"
  lrelu_slope: 0.1
preprocessing:
  threads: 4
  f0_min: 40
  f0_max: 2200
  pitch_extractor:
    name: "ParselmouthPE"
    keep_zeros: False
  separate_sp_ap: False
  vuv: True
  vuv_from_f0: False
  vuv_smoothing: 5
  oversampling: 1
