type: "VUV"
precision: "16-mixed"
val_check: 5000
sample_rate: 44100
f_min: 40
f_max: 16000
n_mels: 128
hop_length: 512
win_length: 2048
n_fft: 2048
lr: 0.00001
lr_decay: 0.99
adam_b1: 0.8
adam_b2: 0.99
use_vuv: True
dataset:
  train:
    path: "dataset/train"
    segment_length: 32768
    return_vuv: True
    pitch_shift: [-12, 12]
    loudness_shift: [0.25, 1.0]
  valid:
    path: "dataset/valid"
    return_vuv: True
    segment_length: Null
    pitch_shift: Null
    loudness_shift: Null
dataloader:
  train:
    batch_size: 20
    shuffle: True
    num_workers: 8
    pin_memory: True
    drop_last: True
    persistent_workers: True
  valid:
    batch_size: 4
    shuffle: False
    num_workers: 4
    pin_memory: True
    drop_last: True
    persistent_workers: True
model:
  lrelu_slope: 0.02
  input_noise: 0.01
  channels: 512
  layers: 4
preprocessing:
  f0_min: 40
  f0_max: 1400
  pitch_extractor:
    name: "ParselmouthPE"
    keep_zeros: False
  spectogram: False
  vuv: True
